### ISSUE TITLE
pm status show 

### ISSUE THREAD

**Issue by LiangYuanchen** [coderofsalvation/pm.sh#1]
I test " automatically restart process",like this

> pm status
> APP                  STATUS   PORT   RESTARTS   USER       PID %CPU %MEM    VSZ   RSS TTY
> provider-order       running  none   0          dev      19498  0.0  0.0   4324   356 pts/0
> 
> kill -9 19498
> APP                  STATUS   PORT   RESTARTS   USER       PID %CPU %MEM    VSZ   RSS TTY
> provider-order       stopped  none   0  

the APP "provider-order" now pid is changed, but can not show at "pm status"

**Comment by LiangYuanchen** [comment]
when I kill this APP "provider-order" again, it really be killed and do not restart once more

**Comment by coderofsalvation** [comment]
Ideally you should not manually kill pids (hence pm is a process manager).
You should use `pm stop <..>` (that will kill the whole process tree).

pm only shows the parent process, but not the child process(es).
try `ps -eH` after `pm restart provider-order` and you'll see the process-tree.

reason: a pid/process can span children processes (which have their own pids). Killing the parent pid will not necessarely kill the children. This is one of the issues `pm.sh` tries to solve.

> Idea: we could introduce an extra flag `pm show -v` (verbose) which shows all child processes as well. What do you think?
