### ISSUE TITLE
No executable in package.json

### ISSUE THREAD

**Issue by KrisZane** [coderofsalvation/pm.sh#4]
Hey man, awesome package, thumbs up for fighting the good fight. 👍 

So I was wondering if you couldn't add
`"bin" : { "pm" : "./bin/pm" }`
to your package.json, so the binary would automatically be installed on path?

**Comment by coderofsalvation** [comment]
hi :D

what's the difference between that and the current?

`"bin" : { "pm" : "bin/pm" }`

**Comment by KrisZane** [comment]
@coderofsalvation No difference at all. :P
You added it about a year ago though and this issues is a bit over 2 years old. So I am guessing it was actually fixed. :P

**Comment by coderofsalvation** [comment]
this is the most hilarious issue ever written on github :)
