### ISSUE TITLE
shopt: lastpipe: invalid shell option name

### ISSUE THREAD

**Issue by TrevorSayre** [coderofsalvation/pm.sh#5]
When running in a remote shell using zsh I get the following:

`~/bin/pm: line 12: shopt: lastpipe: invalid shell option name`

[L12](https://github.com/coderofsalvation/pm.sh/blob/61423842d19b466fb91ff6e426c3f5d3c3fac28c/bin/pm#L12) being
`shopt -s lastpipe              # flexible while loops (maintain scope)`

Not sure the proper route to handle this.

**Comment by coderofsalvation** [comment]
lastpipe was introduced in bash 4.2, see the changelog: http://tiswww.case.edu/php/chet/bash/NEWS.

It might just run without that line but haven't tried.
